language: elixir
elixir:
  - 1.3.4
  - 1.4.4
otp_release:
  - 18.3
services: docker
notifications:
  recipients:
    - elixmoon@gmail.com
    - jquadrin@gmail.com
sudo: false
env:
    matrix:
        - DB=mariadb:10.1
        - DB=mariadb:10.2
        - DB=mariadb:10.3
        - DB=mysql:8.0
        - DB=mysql:5.7
        - DB=mysql:5.6
before_install:
    - sudo service mysql stop
    - docker pull $DB || true
    - docker run --name mariadb -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=1 -d $DB
script: "mix test --cover"
